/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadiologyRouteImport } from './routes/radiology'
import { Route as PhysioRouteImport } from './routes/physio'
import { Route as PharmacistRouteImport } from './routes/pharmacist'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as MinistryRouteImport } from './routes/ministry'
import { Route as LabRouteImport } from './routes/lab'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as IndexRouteImport } from './routes/index'

const RadiologyRoute = RadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioRoute = PhysioRouteImport.update({
  id: '/physio',
  path: '/physio',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistRoute = PharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistryRoute = MinistryRouteImport.update({
  id: '/ministry',
  path: '/ministry',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/community': typeof CommunityRoute
  '/doctor': typeof DoctorRoute
  '/emergency': typeof EmergencyRoute
  '/lab': typeof LabRoute
  '/ministry': typeof MinistryRoute
  '/nurse': typeof NurseRoute
  '/pharmacist': typeof PharmacistRoute
  '/physio': typeof PhysioRoute
  '/radiology': typeof RadiologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/community': typeof CommunityRoute
  '/doctor': typeof DoctorRoute
  '/emergency': typeof EmergencyRoute
  '/lab': typeof LabRoute
  '/ministry': typeof MinistryRoute
  '/nurse': typeof NurseRoute
  '/pharmacist': typeof PharmacistRoute
  '/physio': typeof PhysioRoute
  '/radiology': typeof RadiologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/community': typeof CommunityRoute
  '/doctor': typeof DoctorRoute
  '/emergency': typeof EmergencyRoute
  '/lab': typeof LabRoute
  '/ministry': typeof MinistryRoute
  '/nurse': typeof NurseRoute
  '/pharmacist': typeof PharmacistRoute
  '/physio': typeof PhysioRoute
  '/radiology': typeof RadiologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/community'
    | '/doctor'
    | '/emergency'
    | '/lab'
    | '/ministry'
    | '/nurse'
    | '/pharmacist'
    | '/physio'
    | '/radiology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/community'
    | '/doctor'
    | '/emergency'
    | '/lab'
    | '/ministry'
    | '/nurse'
    | '/pharmacist'
    | '/physio'
    | '/radiology'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/community'
    | '/doctor'
    | '/emergency'
    | '/lab'
    | '/ministry'
    | '/nurse'
    | '/pharmacist'
    | '/physio'
    | '/radiology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRoute
  CommunityRoute: typeof CommunityRoute
  DoctorRoute: typeof DoctorRoute
  EmergencyRoute: typeof EmergencyRoute
  LabRoute: typeof LabRoute
  MinistryRoute: typeof MinistryRoute
  NurseRoute: typeof NurseRoute
  PharmacistRoute: typeof PharmacistRoute
  PhysioRoute: typeof PhysioRoute
  RadiologyRoute: typeof RadiologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radiology': {
      id: '/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof RadiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio': {
      id: '/physio'
      path: '/physio'
      fullPath: '/physio'
      preLoaderRoute: typeof PhysioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist': {
      id: '/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof PharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministry': {
      id: '/ministry'
      path: '/ministry'
      fullPath: '/ministry'
      preLoaderRoute: typeof MinistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRoute,
  CommunityRoute: CommunityRoute,
  DoctorRoute: DoctorRoute,
  EmergencyRoute: EmergencyRoute,
  LabRoute: LabRoute,
  MinistryRoute: MinistryRoute,
  NurseRoute: NurseRoute,
  PharmacistRoute: PharmacistRoute,
  PhysioRoute: PhysioRoute,
  RadiologyRoute: RadiologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
